/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricity.billining.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Adminreji extends javax.swing.JFrame {

    /**
     * Creates new form Adminreji
     */
    public Adminreji() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lbladminid = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        txtadminid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        btnreji = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registration");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1086, -1));

        lblemail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblemail.setText("Email");
        getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 358, -1, -1));

        lbladminid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbladminid.setText("Adimin Id");
        getContentPane().add(lbladminid, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 111, 27));

        lblusername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblusername.setText("Username");
        getContentPane().add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 530, 70, -1));

        lblname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblname.setText("Name");
        getContentPane().add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 273, 70, 28));

        lblpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblpass.setText("Password");
        getContentPane().add(lblpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 616, 98, -1));

        lblphone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblphone.setText("Phone");
        getContentPane().add(lblphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 434, 70, -1));

        txtadminid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadminidActionPerformed(evt);
            }
        });
        getContentPane().add(txtadminid, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 179, 300, 40));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 268, 300, 40));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 349, 300, 40));
        getContentPane().add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 425, 300, 40));
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 521, 300, 40));
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 607, 300, 40));

        btnreji.setText("Register");
        btnreji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrejiActionPerformed(evt);
            }
        });
        getContentPane().add(btnreji, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 709, 100, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Sign In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 708, 100, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 706, 109, 44));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electricity/billining/system/hicon1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 146, 339, 646));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrejiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrejiActionPerformed
        // TODO add your handling code here:
        try
        {
            String adminid,name,email,tp,username,password;
            adminid=txtadminid.getText();
            name=txtname.getText();
            email=txtemail.getText();
            tp=txtphone.getText();
            username=txtusername.getText();
            password=txtpass.getText();
             {
            if(adminid.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please enter admin id");
            }
             if(name.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please enter name");
            }
            if(email.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please enter email");
            }
             if( tp.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please enter phone ");
            }
              if(username.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please enter username");
            }
               if(password.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please enter password");
            }
            }
            
            
            String dbpath="jdbc:mysql://localhost/elecricitymanagement";
        Connection con=DriverManager.getConnection(dbpath,"root","");
        Statement st =con.createStatement();
        st.executeUpdate("insert into adminregi Values('"+adminid+"','"+name+"','"+email+"','"+tp+"','"+username+"','"+password+"')");
       JOptionPane.showMessageDialog(this,"Registation Successfull");
        }
         catch(Exception ex)
               {
                   JOptionPane.showMessageDialog(null,ex.getMessage());
               }
    }//GEN-LAST:event_btnrejiActionPerformed

    private void txtadminidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadminidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadminidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Login frl=new Login();
        frl.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtadminid.setText(null);
          txtname.setText(null);
           txtemail.setText(null);
              txtphone.setText(null);
               txtusername.setText(null);
                  txtpass.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminreji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminreji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminreji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminreji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminreji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreji;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbladminid;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtadminid;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
