/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricity.billining.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class MeterDetails extends javax.swing.JFrame {

    /**
     * Creates new form MeterDetails
     */
    public MeterDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbmtype = new javax.swing.JPanel();
        lblcnic = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblmtype = new javax.swing.JLabel();
        lblphasecode = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcnic = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cmbmlocation = new javax.swing.JComboBox<>();
        cmbaa = new javax.swing.JComboBox<>();
        cmbpcode = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblmnum = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        btnsub = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Meter Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        cmbmtype.setBackground(new java.awt.Color(0, 153, 204));
        cmbmtype.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcnic.setText("Search Customer Nic");
        cmbmtype.add(lblcnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 129, -1));

        jLabel4.setText("Meter Nubmer");
        cmbmtype.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 90, 20));

        jLabel5.setText("Meter Location");
        cmbmtype.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 141, 110, -1));

        lblmtype.setText("Meter Type");
        cmbmtype.add(lblmtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 209, 90, -1));

        lblphasecode.setText("Phase Code");
        cmbmtype.add(lblphasecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 286, 80, -1));

        jLabel8.setText("Days");
        cmbmtype.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 383, 37, -1));

        jLabel9.setText("Note");
        cmbmtype.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 455, 37, -1));
        cmbmtype.add(txtcnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 162, -1));

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        cmbmtype.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 19, -1, -1));
        cmbmtype.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 68, 43, -1));

        cmbmlocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inside", "Outside" }));
        cmbmtype.add(cmbmlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 160, 30));

        cmbaa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electric Meter", "Smart Meter" }));
        cmbmtype.add(cmbaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 160, 40));

        cmbpcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "011", "022", "033", "044", "055" }));
        cmbmtype.add(cmbpcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 150, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setText("30  DAYS");
        cmbmtype.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 383, 134, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setText("By Default Bill Calculate 30 Day Only");
        cmbmtype.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 438, 404, -1));
        cmbmtype.add(lblmnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 120, 40));

        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        btnsub.setText("Submit");
        btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnnext.setText("Next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electricity/billining/system/bill.png"))); // NOI18N

        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnhome)
                        .addGap(66, 66, 66)
                        .addComponent(btnsub)
                        .addGap(64, 64, 64)
                        .addComponent(btnback)
                        .addGap(79, 79, 79)
                        .addComponent(btnnext)
                        .addGap(86, 86, 86)
                        .addComponent(btnclose))
                    .addComponent(cmbmtype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbmtype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhome)
                    .addComponent(btnsub)
                    .addComponent(btnback)
                    .addComponent(btnnext)
                    .addComponent(btnclose))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubActionPerformed
        // TODO add your handling code here:
           try{
        String m_no,m_location,m_type,phase_c;
        
       m_no=lblmnum.getText();
     m_location=cmbmlocation.getSelectedItem().toString();
     m_type=cmbaa.getSelectedItem().toString();
     phase_c=cmbpcode.getSelectedItem().toString();
       if(m_no.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please enter meter number");
            }
           
            if(  m_location.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please enter meter location");
            }
             if( m_type.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please enter phone meter type");
            }
              if(phase_c.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please enter phase code");
            }
             
         String dbpath="jdbc:mysql://localhost/elecricitymanagement";
        Connection con=DriverManager.getConnection(dbpath,"root","");
        Statement st =con.createStatement();
        st.executeUpdate("insert into  meter_detail Values('"+m_no+"','"+ m_location+"','"+m_type+"','"+phase_c+"')");
         JOptionPane.showMessageDialog(this,"Registation Successfull");
         
       }
       catch(Exception ex)
               {
                   JOptionPane.showMessageDialog(null,ex.getMessage());
               }
                                           


    }//GEN-LAST:event_btnsubActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
           try{
       String c_nic=txtcnic.getText();
       
       String dbpath="jdbc:mysql://localhost/elecricitymanagement";
        Connection con=DriverManager.getConnection(dbpath,"root","");
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select M_no from customer_detail ");
        while(rs.next())
        {
            c_nic=rs.getString(1);
        }
        
        lblmnum.setText( c_nic);
       
          
        
        }
        catch(Exception ex)
               {
                   JOptionPane.showMessageDialog(null,ex.getMessage());
               }
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
         Home h1=new  Home();
        h1.show();
        dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        CustomerDetails frl=new  CustomerDetails();
        frl.show();
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
         Billcalculate frl=new   Billcalculate();
        frl.show();
        dispose();
    }//GEN-LAST:event_btnnextActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeterDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsub;
    private javax.swing.JComboBox<String> cmbaa;
    private javax.swing.JComboBox<String> cmbmlocation;
    private javax.swing.JPanel cmbmtype;
    private javax.swing.JComboBox<String> cmbpcode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcnic;
    private javax.swing.JLabel lblmnum;
    private javax.swing.JLabel lblmtype;
    private javax.swing.JLabel lblphasecode;
    private javax.swing.JTextField txtcnic;
    // End of variables declaration//GEN-END:variables
}
