/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricity.billining.system;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DELL
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbladmindetails = new javax.swing.JLabel();
        btnclick1 = new javax.swing.JButton();
        lblcusdetails = new javax.swing.JLabel();
        click2 = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Report");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(420, 420, 420))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbladmindetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbladmindetails.setText("Admin Details");
        jPanel2.add(lbladmindetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 168, 39));

        btnclick1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnclick1.setText("Click");
        btnclick1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclick1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnclick1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 200, 40));
        btnclick1.getAccessibleContext().setAccessibleDescription("");

        lblcusdetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblcusdetails.setText("Customer Details");
        jPanel2.add(lblcusdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        click2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        click2.setText("Click");
        click2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                click2ActionPerformed(evt);
            }
        });
        jPanel2.add(click2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 200, 40));
        click2.getAccessibleContext().setAccessibleDescription("");

        btnhome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnclick1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclick1ActionPerformed
        // TODO add your handling code here:
        try
        {
            String dbpath="jdbc:mysql://localhost/elecricitymanagement";
        Connection con=DriverManager.getConnection(dbpath,"root","");
        String path=("C:\\Users\\DELL\\OneDrive\\Documents\\NetBeansProjects\\Electricity Billining System\\src\\electricity\\billining\\system\\report.jrxml");
        JasperReport jr;
        jr=JasperCompileManager.compileReport(path);
        JasperPrint print=JasperFillManager.fillReport(jr,null,con);
        JasperViewer.viewReport(print,false);
        
        }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnclick1ActionPerformed

    private void click2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_click2ActionPerformed
        // TODO add your handling code here:
         try
        {
            String dbpath="jdbc:mysql://localhost/elecricitymanagement";
        Connection con=DriverManager.getConnection(dbpath,"root","");
        String path=("C:\\Users\\DELL\\OneDrive\\Documents\\NetBeansProjects\\Electricity Billining System\\src\\electricity\\billining\\system\\report3.jrxml");
        JasperReport jr;
        jr=JasperCompileManager.compileReport(path);
        JasperPrint print=JasperFillManager.fillReport(jr,null,con);
        JasperViewer.viewReport(print,false);
        
        }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_click2ActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
        Home h1=new  Home();
        h1.show();
        dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclick1;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton click2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbladmindetails;
    private javax.swing.JLabel lblcusdetails;
    // End of variables declaration//GEN-END:variables
}
